In [1]:
import numpy as np

In [ ]:
my_list = [1,2,3]

In [ ]:
my_array = np.array([1,2,3])

In [ ]:
print(type(my_list))

In [ ]:
print(np.array(my_list))

In [ ]:
print(np.arange(0,10))

In [ ]:
print(np.arange(0,11,2))

In [ ]:
print(np.zeros(3))

In [ ]:
print(np.zeros((5,5)))

In [ ]:
np.ones(3)

In [ ]:
np.ones((3,3))

In [ ]:
print(np.linspace(0,10,3))
print(np.linspace(0,5,20))
print(np.linspace(0,5,21))

In [ ]:
print(np.random.rand(2))

In [ ]:
print(np.random.rand(5,5))

In [ ]:
#Same for same seed
np.random.seed(47)
print(np.random.rand(4))

In [ ]:
print(np.random.randint(1,100))

In [ ]:
print(np.random.randint(1,100,10))

In [ ]:
#Same for same seed 77
np.random.seed(77)
print(np.random.rand(4))

In [ ]:
#Same for same seed 77
np.random.seed(77)
print(np.random.rand(4))

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
print(arr)
print(ranarr)

In [ ]:
arr.reshape(5,5)

In [ ]:
ranarr.max()

In [ ]:
ranarr.argmax()

In [ ]:
ranarr.min()

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr[1:5]

In [ ]:
arr[0:5]

In [ ]:
arr[0:5] = 100
arr

In [ ]:
arr = np.arange(0,11)
arr

In [ ]:
slice_of_arr = arr[0:6]
print(slice_of_arr)
print(arr)

In [ ]:
slice_of_arr[:] = 99
slice_of_arr

In [ ]:
arr_copy = arr.copy()
arr_copy

In [ ]:
#Conditional selection
arr = np.arange(1,11)
arr

In [ ]:
#Check if element > 4, return True / False
bool_arr = arr>4
bool_arr

In [ ]:
#print only the True indexes
arr[bool_arr]

In [3]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
print(arr/arr) #Fills division by zero with nan

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


<ipython-input-9-00bb58cbf2e7>:1: RuntimeWarning: invalid value encountered in divide
  print(arr/arr)


In [8]:
arr*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [10]:
print(1/arr) #Fills with infinity

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]


<ipython-input-10-1c9f9dd9e051>:1: RuntimeWarning: divide by zero encountered in divide
  print(1/arr)


In [11]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [12]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [13]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [14]:
np.log(arr)

<ipython-input-14-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [15]:
#Summary Statistics

In [16]:
arr.sum()

45

In [17]:
arr.mean()

4.5

In [18]:
arr.max()

9

In [21]:
arr.min()

0

In [22]:
arr.var()

8.25

In [23]:
arr.std()

2.8722813232690143

In [24]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
arr_2d.shape

(3, 4)

In [26]:
arr_2d.sum(axis=0) #column-wise

array([15, 18, 21, 24])

In [27]:
arr_2d.sum(axis=1) #row-wise

array([10, 26, 42])

### Assignment 1


In [47]:
import numpy as np

# 1. Create an array of 10 zeros
array_zeros = np.zeros(10)
print("Array of 10 zeros:", array_zeros)

# 2. Create an array of 10 ones
array_ones = np.ones(10)
print("Array of 10 ones:", array_ones)

# 3. Create an array of 10 fives
array_fives = np.full(10, 5)
print("Array of 10 fives:", array_fives)

# 4. Create an array of the integers from 10 to 50
array_integers = np.arange(10, 51)
print("Array of integers from 10 to 50:", array_integers)

# 5. Create an array of all the even integers from 10 to 50
array_even_integers = np.arange(10, 51, 2)
print("Array of even integers from 10 to 50:", array_even_integers)

# 6. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 matrix with values from 0 to 8:\n", matrix_3x3)

# 7. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3x3 identity matrix:\n", identity_matrix)

# 8. Use numpy to generate a random number between 0 and 1
random_number = np.random.rand()
print("Random number between 0 and 1:", random_number)

# 9. Use numpy to generate an array of 25 random numbers sampled from a standard normal distribution
random_normal_array = np.random.randn(25)
print("Array of 25 random numbers from standard normal distribution:", random_normal_array)

# 10. Create an array of 20 linearly spaced points between 0 and 1
linear_spaced_array = np.linspace(0, 1, 20)
print("Array of 20 linearly spaced points between 0 and 1:", linear_spaced_array)


Array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of 10 fives: [5 5 5 5 5 5 5 5 5 5]
Array of integers from 10 to 50: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
Array of even integers from 10 to 50: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
3x3 matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random number between 0 and 1: 0.29440515456796934
Array of 25 random numbers from standard normal distribution: [ 0.36350814  1.11243354  1.30338289 -0.95403322  0.73740134  0.99098824
 -1.42572651  1.6385564   1.7803807  -0.8944399  -0.95956961 -0.34326509
  0.2940055   0.74631739  1.12493315 -0.12178334  0.44000322 -0.9767536
  1.6624871  -2.72354464 -1.02331736  1.69353643 -0.03062582  2.10093431
 -1.32518524]
Array of 20 linearly spaced points between 0 and 1: [0